### ISSUE TITLE
Image not compatible with mariadb 10.4

### ISSUE THREAD

**Issue by b-bittner** [linuxserver/docker-tt-rss#38]
I had a compose file like this:
```
version: '2'
...
services:
  db:
    image: mariadb
    ...
  app:
    image: linuxserver/tt-rss
...
```
Everything was working fine for months now, but since last week the system doesn't Update the feeds anymore.
I spend a lot of time for debugging without finding anything:
* no error
* no fail
* no log or debug
* manual update via GUI with 'fD' was fine
* manual single feed update via cmd in container was also fine
* manual starting autoupdate (with debug): no success and still no error or fail

I then found out, that at the same time the updates stopped, my system (watchtower) updated mariadb:latest from 10.3.x to 10.4.x.
I manually downgraded to 10.3 again (image "mariadb:10.3-bionic") and now everything is fine again, updates are running automatically now.

I don't understand way and especially not why there are no error and why I was able to update the feeds manually.
I'm also not sure whether this is a linuxserver docker-image problem or a tt-rss problem.

So maybe you have a better understanding of you build so you can find the root cause of the problem. Or at least add a hint to the README.md for compatibility issues.

I'm eager to help, just let me know.

**Comment by thelamer** [comment]
Please report this upstream: 
https://discourse.tt-rss.org/

We do also provide a Maridb container: (we are locked at 10.3 because of compatibility problems like this)
https://hub.docker.com/r/linuxserver/mariadb

I understand your concern but I think in this case the issue is so specific that it really falls on the upstream developers to fix and or acknowledge and not for us to be maintaining rolling documentation on database compatibility.

**Comment by sparklyballs** [comment]
i'm running this container with a 10.4.6 mariadb  instance, so the image is not incompatible with 10.4

![Screenshot_20190704_000026](https://user-images.githubusercontent.com/4343808/60629750-e0c07f80-9dee-11e9-8fe6-a947bae22232.jpeg)

I suggest that the issue is with mariadb and upgrading the database. 

https://mariadb.com/kb/en/library/upgrading-from-mariadb-103-to-mariadb-104/

**Comment by Nebucatnetzer** [comment]
Is this something we should add to the readme?
I ran into the same problem when upgrading my containers.

**Comment by aptalca** [comment]
no need to add to the readme because:
1) it seems to be an upstream restriction
2) it works with our mariadb image

**Comment by Nebucatnetzer** [comment]
Sure however AFAIK it's not mentioned that one should be using your mariadb image, right?
 I don't know about other users but I usually use stuff directly from the developer and in the newest version if possible.
 When it is an upstream problem we could add it temporarily to the readme until it is solved upstream?

Fri Jul 26 20:05:17 GMT+02:00 2019 aptalca <notifications@github.com>:
